platform: linux

image_resource:
  type: docker-image
  source:
    repository: cypress/base
    tag: 10

inputs:
- name: census-worth-self-help

outputs:
- name: mochawesome-report
  path: census-worth-self-help/site/mochawesome-report
- name: coverage
  path: census-worth-self-help/site/coverage

caches:
- path: .npm
- path: .cypress-cache

params:
  GATSBY_ASSETS_PATH: ((gatsby.assets-path))
  GATSBY_CHAT_BUTTON_CONTAINER_ID: ((gatsby.chat-button-container-id))
  GATSBY_CHAT_CHANNEL: ((gatsby.chat-channel))
  GATSBY_CHAT_DOMAIN: ((gatsby.chat-domain))
  GATSBY_CHAT_TENANT: ((gatsby.chat-tenant))
  GATSBY_CHAT_UUID: ((gatsby.chat-uuid))

run:
  path: sh
  args:
  - -exec
  - |
    echo "Testing"
    export ROOT_FOLDER=$(pwd)
    export CYPRESS_CACHE_FOLDER=${ROOT_FOLDER}/.cypress-cache
    cd census-worth-self-help/site
    builddir="_build/content/"
    mkdir -p "$builddir" && cp -R ../content/ "$builddir"
    assetdir="static/assets/"
    rm -rf "$assetdir"
    cp -R ../static/assets "$assetdir"
    npm ci
    npm run coverage
    # ONS-289
    sed -i 's/smokeTestTimeout: 10000/smokeTestTimeout: 60000/' node_modules/cypress/lib/tasks/verify.js
    npm run e2e
    npm run merge-reports
    