backend:
  name: github
  repo: ONSdigital/census-worth-self-help
  branch: test_content
  squash_merges: true

media_folder: static/assets
public_folder: assets

collections:
  - name: articles
    label: Articles
    label_singular: 'Article' # Used in the UI, ie: "New Post"
    folder: content/articles
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Publish Date, widget: date }
      - { name: description, label: Description }
      - { name: body, label: Main Body, widget: markdown }
      - { label: "Repo",
          name: "repo",
          widget: "relation",
          collection: "repos",
          searchFields: ["title"],
          valueField: "title",
          displayFields: ["title"]}
      - { name: priority, label: Priority, widget: "number", default: 0,
          hint: "Controls the order in which the repo appears in the parent repo, starting from 0, lower = higher"  }
      - { name: role, label: Role, required: false }
      - { name: author, label: Author, required: false }
      - { name: reviewedby, label: Reviewed By, required: false }
      - { name: signedby, label: Signed Off, required: false }
      - { name: tags, label: Tags, widget: "list", required: false }


  - name: repos
    label: Repos
    label_singular: 'Repo' # Used in the UI, ie: "New Post"
    folder: content/repos
    create: true
    fields:
      - { name: title, label: Title }
      - { label: "Repo",
          name: "repo",
          widget: "relation",
          collection: "repos",
          searchFields: ["title"],
          valueField: "title",
          displayFields: ["title"],
          hint: "Enter the parent repo for this repo, be careful not to create a loop.",
          required: false }
      - { name: priority, label: Priority, widget: "number", default: 0,
          hint: "Controls the order in which the repo appears in the parent repo, starting from 0, lower = higher"  }


  - name: constants
    label: Constants
    create: false
    delete: false
    files:
      - file: "content/constants/alert.md"
        label: "Alert"
        name: "alert"
        fields:
          - { label: 'Content', name: 'alert_content', widget: 'string', required: false }