backend:
  name: github
  repo: ONSdigital/census-worth-self-help-test
  branch: master
  squash_merges: true
  base_url: https://oauth.worth.census-gcp.onsdigital.uk/
  cache_mode: optimised
  max_unpublished: 40

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: articles
    label: Articles
    label_singular: 'Article'
    folder: content/articles
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Publish Date, widget: datetime }
      - { name: description, label: Description }
      - { name: body, label: Main Body, widget: sanitiziedMarkdown }
      - { label: "Directory",
          name: "directory",
          widget: "relation",
          collection: "directories",
          searchFields: ["title"],
          valueField: "title",
          displayFields: ["title"] }
      - { name: priority, label: Priority, widget: "number", default: 0,
          hint: "Controls the order in which the directory appears in the parent directory, starting from 0, lower = higher"  }
      - { name: role, label: Role, required: false }
      - { name: author, label: Author, required: false }
      - { name: reviewedby, label: Reviewed By, required: false }
      - { name: signedby, label: Signed Off, required: false }
      - { name: tags, label: Tags, widget: "list", required: false,
          hint: "divide tags up using commas, e.g:  emergency, test, contact. The following tags have effects: draft, webchat, popular " }
      - { label: "Related Departments",
          name: "departments",
          widget: "relation",
          collection: "departments",
          searchFields: ["title"],
          valueField: "title",
          displayFields: ["title"],
          multiple: true }

  - name: departments
    label: Departments
    label_singular: 'Department'
    folder: content/departments
    create: true
    fields:
    - { name: title, label: Title }
    - { name: description, label: Description }

  - name: directories
    label: Directories
    label_singular: 'Directory'
    folder: content/directories
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { label: "Directory",
          name: "directory",
          widget: "relation",
          collection: "directories",
          searchFields: ["title"],
          valueField: "title",
          displayFields: ["title"],
          hint: "Enter the parent directory for this directory, be careful not to create a loop.",
          required: false }
      - { name: priority, label: Priority, widget: "number", default: 0,
          hint: "Controls the order in which the directory appears in the parent directory, starting from 0, lower = higher"  }


  - name: constants
    label: Constants
    create: false
    delete: false
    files:
      - file: "content/constants/alert.md"
        label: "Alert"
        name: "alert"
        fields:
          - { label: 'Title', name: 'alert_title', widget: 'string', required: false }
          - { label: 'Content', name: 'body', widget: 'markdown', required: false,
              hint: "If the content is empty no alert will show." }

      - file: "content/constants/contact_centre_details.md"
        label: "Contact centre details"
        name: "contact_centre_details"
        fields:
          - { label: 'Phone number', name: 'contact_centre_number', widget: 'string', required: true }
          - { label: 'Text shown on contact centre page', name: 'contact_centre_text', widget: 'text', required: true }

